apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.name" . }}-config
data:
  redis-master.conf: |
    cluster-enabled yes
    cluster-config-file /usr/local/etc/redis/nodes.conf
    cluster-node-timeout 5000
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync everysec
    bind 0.0.0.0
    port 6379

  redis-replica.conf: |
    cluster-enabled yes
    cluster-config-file /usr/local/etc/redis/nodes.conf
    cluster-node-timeout 5000
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync everysec
    bind 0.0.0.0
    port 6379