apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis.name" . }}-replica-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}