apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.name" . }}-replica
  labels:
    app: redis
    role: replica
spec:
  ports:
    - port: 6379
  selector:
    app: redis
    role: replica
